image: docker:latest
stages:
  - build jar
  - build and push docker image
  - deploy

build:
  image: maven:3.6.3-jdk-11-slim
  stage: build jar
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
  script:
    - mvn clean install -Dspring.profiles.active=$SPRING_ACTIVE_PROFILE --quiet
  artifacts:
    paths:
      - target/*.jar
    expire_in: 15 mins
  only:
    - main

docker build:
  stage: build and push docker image
  before_script:
    - source .${CI_COMMIT_REF_NAME}.env
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  after_script:
    - docker logout
  script:
    - docker build --build-arg SPRING_ACTIVE_PROFILE=$SPRING_ACTIVE_PROFILE --quiet -t $DOCKER_REPO .
    - docker push --quiet $DOCKER_REPO
    - docker rmi --force $DOCKER_REPO
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - source .${CI_COMMIT_REF_NAME}.env
  script:
    - ssh msiazure@$SERVER "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; docker stop $APP_NAME; docker system prune -a -f; docker pull $DOCKER_REPO; docker container run -d --name $APP_NAME -p $PORT:8080 -e SPRING_PROFILES_ACTIVE=$SPRING_ACTIVE_PROFILE $DOCKER_REPO; docker logout"
  only:
    - main
